name = "media-gate"
main = "worker.js"
compatibility_date = "2025-05-15"
compatibility_flags = ["nodejs_compat"]

[vars]
BASE_DOMAIN = "anybodyiskiller.shop"

[[d1_databases]]
binding = "DB"
database_name = "media-store"
database_id = "dfff5cd4-1df8-4b31-b9f8-d48bd9729566"

[[routes]]
pattern = "media.anybodyiskiller.shop"
custom_domain = true
